rango/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('rango/', include('rango_core.urls')),
    path('admin/', admin.site.urls),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango_core/urls.py
from django.urls import path

from . import views

app_name = 'rango_core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show-category'),
    path('category/<slug:category_name_slug>/add-page/', views.add_page, name='add-page'),
    path('add-category/', views.add_category, name='add-category'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('restricted/', views.restricted, name='restricted'),

]

rango_core/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify


class Category(models.Model):
    max_lengths = {'name': 128}
    max_lengths['slug'] = max_lengths['name']

    # blank = False  - by default for fields
    # null = False - by default for fields
    # but TextField and CharField always stores ONLY ""(empty string), and never 'null'

    name = models.CharField(max_length=max_lengths['name'], unique=True,
                            blank=False, null=False)

    likes = models.IntegerField(default=0,
                                blank=False, null=False)

    views = models.IntegerField(default=0,
                                blank=False, null=False)

    slug = models.SlugField(max_length=max_lengths['name'], unique=True,
                            blank=False, null=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class Page(models.Model):
    max_lengths = {'title': 128, 'url': 200}

    # related_name='pages' - param of ForeignKey? What does?
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE)

    title = models.CharField(max_length=max_lengths['title'],
                             blank=False, null=False)

    url = models.URLField(max_length=max_lengths['url'],
                          blank=False, null=False)

    views = models.IntegerField(default=0,
                                blank=False, null=False)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    max_lengths = {'website': 200}

    user = models.OneToOneField(to=User, on_delete=models.CASCADE)

    #
    website = models.URLField(max_length=max_lengths['website'],
                              blank=True, null=False)

    picture = models.ImageField(upload_to='profile_images',
                                blank=True, null=False)

    def __str__(self):
        return f'{self.user.username}\'s profile'

rango_core/forms.py
from django import forms
from django.contrib.auth.models import User

from . import models


class UserForm(forms.ModelForm):
    # overriding User's model field 'password' with field's own field 'password'
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        # required for both fields should be FALSE(!),
        # because  'blank=True' in model
        # correlates with 'required=False' in modelform
        model = models.UserProfile
        fields = ('website', 'picture')


class CategoryForm(forms.ModelForm):
    # required = True  - by default
    name = forms.CharField(help_text='Please enter the category name.',
                           max_length=models.Category.max_lengths.get('name'))

    # because we handle slugs db saving in the overridden 'save()'
    # method inside the Category class (imported from models.py)
    # we manually set required as False
    slug = forms.CharField(widget=forms.HiddenInput(), required=False,
                           max_length=models.Category.max_lengths.get('slug'))

    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = models.Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(help_text='Please enter the title of the page.',
                            max_length=models.Page.max_lengths.get('title'))

    url = forms.URLField(help_text='Please enter the URL of the page.',
                         max_length=models.Page.max_lengths.get('url'))

    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = models.Page
        exclude = ('category',)

    # example of the pre-cleaning of data. after send to validators
    # def clean(self):
    #     cleaned_data = self.cleaned_data
    #     url = cleaned_data.get('url')
    #
    #     if url and not url.startswith('http://'):
    #         url = 'http://' + url
    #         cleaned_data['url'] = url
    #
    #     return cleaned_data

rango_core/views.py
from datetime import datetime

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse

from . import forms, models


def get_server_side_cookies(request, cookie, default_value=None):
    tweaked_cookie = request.session.get(cookie, default_value)
    return tweaked_cookie


def visitor_cookie_handler(request):
    # getting the number of user's visits from cookie
    # if no such cookie --> user's first visit
    visits = int(get_server_side_cookies(request, 'visits', '1'))

    # getting the datetime of user's visits from cookie
    # if no such cookie --> user's first visit datetime
    last_visit_cookie = get_server_side_cookies(request, 'last_visit', str(datetime.now()))

    last_visit_time = datetime.strptime(last_visit_cookie[:-7],  # getting rid of micro/nano secs
                                        '%Y-%m-%d %H:%M:%S')  # and parsing previous visit time

    # if MORE THAN ONE DAY has passed:
    if (datetime.now() - last_visit_time).days >= 1:
        visits += 1
        request.session['last_visit'] = str(datetime.now())

    else:
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits


def about(request):
    visitor_cookie_handler(request)

    about_context = {
        'visits': request.session.get('visits'),
    }

    return render(request, 'rango_core/about.html', context=about_context)


@login_required
def restricted(request):
    return render(request, 'rango_core/restricted.html')


@login_required
def user_logout(request):
    logout(request)
    return redirect(to=reverse('rango_core:index'))


def user_login(request):
    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)

                return redirect(reverse('rango_core:index'))

            else:
                return HttpResponse('Your Rango account is disabled.')

        else:
            print(f'Invalid login details: {username}, {password}')
            return HttpResponse("Invalid login details supplied.")

    else:
        return render(request, 'rango_core/login.html')


def register(request):
    registered = False

    if request.method == 'POST':

        user_form = forms.UserForm(request.POST)
        profile_form = forms.UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            # SAVING THE USER ---------------------------------
            user = user_form.save(commit=True)

            # set_password hashes the password
            user.set_password(user.password)
            user.save()

            # SAVING THE USER PROFILE --------------------------
            # Since we need to set the user attribute ourselves,
            # we set commit=False. This delays saving the model
            # until we're ready to avoid integrity problems.
            profile: models.UserProfile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES.get('picture')

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = forms.UserForm()
        profile_form = forms.UserProfileForm()

    return render(request, 'rango_core/register.html', {'user_form': user_form,
                                                        'profile_form': profile_form,
                                                        'registered': registered})


def index(request):
    category_query = models.Category.objects.order_by('-likes')[:5]
    pages_query = models.Page.objects.order_by('-views')[:5]

    visitor_cookie_handler(request)

    context_dict = {
        'boldmessage': 'Crunchy, creamy, cookie, candy, cupcake!',
        'categories': category_query,
        'pages': pages_query,
    }

    response = render(request, 'rango_core/index.html', context=context_dict)

    return response


def add_category(request):
    form = forms.CategoryForm()

    if request.method == 'POST':
        form = forms.CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)

            return redirect(to=reverse('rango_core:index'))

        else:
            print(form.errors)

    return render(request, 'rango_core/add_category.html', {'form': form})


def add_page(request, category_name_slug):
    try:
        category = models.Category.objects.get(slug=category_name_slug)
    except models.Category.DoesNotExist:
        category = None

    form = forms.PageForm()
    if request.method == "POST":
        form = forms.PageForm(request.POST)

        if form.is_valid():

            if category:
                page = form.save(commit=False)

                page.category = category
                page.views = 0

                page.save()

                return redirect(reverse('rango_core:show-category', kwargs={'category_name_slug': category_name_slug}))

        else:
            print(form.errors)

    context = {'form': form, 'category': category}
    return render(request, 'rango_core/add_page.html', context=context)


def show_category(request, category_name_slug):
    context = {}

    try:
        category = models.Category.objects.get(slug=category_name_slug)
        pages = models.Page.objects.filter(category=category)
        context['pages'] = pages
        context['category'] = category

    except models.Category.DoesNotExist:
        context['pages'] = None
        context['category'] = None

    return render(request, 'rango_core/category.html', context=context)

templates/rango_core/about.html
{% extends 'rango_core/base.html' %}
{% load static %}

{% block title_block %}
    About Tango with Django!
{% endblock %}


{% block body_block %}

    <h1>Rango says...</h1>

    <p>visits: {{ visits }}</p>

    <div>
        Here is the about page <br/>
        <strong>This tutorial has been put together by Vasiliy Myravyov</strong><br />
    </div>


    <div>
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
        <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat">
    </div>


{% endblock %}

templates/rango_core/add_category.html
{% extends 'rango_core/base.html' %}
{% load static %}

{% block title_block %}
    Add Category!
{% endblock %}


{% block body_block %}

    <h1>Add a Category</h1>

    <div>

        <form action="{% url 'rango_core:add-category' %}" id="category-form" method="POST"> {% csrf_token %}

            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}

            <input type="submit" name="submit" value="Create Category"/>

        </form>

    </div>

{% endblock %}

templates/rango_core/add_page.html
{% extends 'rango_core/base.html' %}
{% load static %}

{% block title_block %}

    {% if category %}
        Add Page to {{ category.name }} Category!
    {% else %}
        Сan't add page to unknown category!
    {% endif %}

{% endblock %}


{% block body_block %}

    {% if category %}

        <h1>Add a Page to The Category: {{ category.name|capfirst }}</h1>

        <form action="{% url 'rango_core:add-page' category.slug %}" id="page-form" method="POST"> {% csrf_token %}

            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }} <br/>
            {% endfor %}

            <input type="submit" name="submit" value="Add Page"/>

        </form>

    {% else %}
        The specified category does not exist!
    {% endif %}

{% endblock %}

templates/rango_core/base.html
<!DOCTYPE html>
{% load static %}
{% load rango_core_template_tags %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>
        Rango -
        {% block title_block %}
            How to Tango with Django!
        {% endblock %}
    </title>
</head>


<body>


<div>
    {% block body_block %}
        This is body_block's default content.
    {% endblock %}
</div>


<div>
    {% block sidebar_block %}
        {% get_category_query category %}
    {% endblock %}
</div>


<hr/>


<div>
    <ul>

        {% if user.is_authenticated %}

            <li><a href="{% url 'rango_core:restricted' %}">Restricted Page</a></li>
            <li><a href="{% url 'rango_core:logout' %}">Logout</a></li>
            <li><a href="{% url 'rango_core:add-category' %}">Add New Category</a></li>

        {% else %}

            <li><a href="{% url 'rango_core:login' %}">Login</a></li>
            <li><a href="{% url 'rango_core:register' %}">Sign Up</a></li>

        {% endif %}

        <li><a href="{% url 'rango_core:about' %}">About</a></li>
        <li><a href="{% url 'rango_core:index' %}">Index</a></li>

    </ul>
</div>


</body>

</html>

templates/rango_core/categories.html
<ul>
    {% if categories %}

        {% for category in categories %}
            {% if category == current_category %}



                <li>
                    <strong>
                        <a href="{% url 'rango_core:show-category' category.slug %}">{{ category.name }}</a>
                    </strong>
                </li>



            {% else %}




                <li>
                    <a href="{% url 'rango_core:show-category' category.slug %}">{{ category.name }}</a>
                </li>



            {% endif %}

        {% endfor %}

    {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

templates/rango_core/category.html
{% extends 'rango_core/base.html' %}
{% load static %}


{% block title_block %}

    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}

{% endblock %}


{% block body_block %}

    {% if category %}

        <h1>{{ category.name }}</h1>

        {% if pages %}

            <ul>
                {% for page in pages %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>

        {% else %}

            <strong>No pages currently in category.</strong>

        {% endif %}

        {% if user.is_authenticated %}
            <a href="{% url 'rango_core:add-page' category.slug %}">Add Page</a>
        {% endif %}

    {% else %}
        The specified category does not exist!
    {% endif %}

{% endblock %}

templates/rango_core/index.html
{% extends 'rango_core/base.html' %}
{% load static %}

{% block title_block %}
    Index of the Tango with Django!
{% endblock %}

{% block body_block %}

    <h1>Rango says...</h1>


    <div>
        {% if user.is_authenticated %}
            howdy {{ user.username }}
        {% else %}
            hey there partner!
        {% endif %}
        {#        <p>visits: {{ visits }}</p>#}

        <br/>

        <strong>{{ boldmessage }}</strong><br/>
    </div>


    <div>
        <h1>Most Liked Categories</h1>
        {% if categories %}
            <ul>
                {% for category in categories %}
                    <li>
                        <a href="{% url 'rango_core:show-category' category.slug %}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no categories present</strong>
        {% endif %}
    </div>


    <div>

        <h1>Most Viewed Pages</h1>

        {% if pages %}

            <ul>
                {% for page in pages %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>

        {% else %}
            <strong>There are no categories present</strong>
        {% endif %}

    </div>


    <div>
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango"/>
    </div>


{% endblock %}

templates/rango_core/login.html
{% extends 'rango_core/base.html' %}
{% load static %}

{% block title_block %}
    Login.
{% endblock %}

{% block body_block %}

    <h1>Login to Rango</h1>

    <form action="{% url 'rango_core:login' %}" id="login_form" method="POST"> {% csrf_token %}
        Username: <input type="text" name="username" size="50"/>
        <br/>
        Password: <input type="password" name="password" size="50"/>
        <br/>
        <input type="submit" name="submit" value="Submit"/>
    </form>




{% endblock %}

templates/rango_core/register.html
{% extends 'rango_core/base.html' %}
{% load static %}




{% block title_block %}
    Register
{% endblock %}



{% block body_block %}

    <h1>Register for Rango</h1>

    {% if registered %}

        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'rango_core:index' %}">Return to the homepage.</a><br/>

    {% else %}

        <form action="{% url 'rango_core:register' %}" id="user_form" method="POST"
              enctype="multipart/form-data"> {% csrf_token %}

            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input type="submit" name="submit" value="Register"/>

        </form>


    {% endif %}

{% endblock %}

templates/rango_core/restricted.html
{% extends 'rango_core/base.html' %}
{% load static %}

{% block title_block %}
    Restricted Page!
{% endblock %}

{% block body_block %}
    <strong> Since you're logged in, you can see this text!</strong>
{% endblock %}